/**
 * Main-owned image generation service (Step 5).
 *
 * Owns provider selection (Heart-aware), credential access, bounded
 * provider calls, fan-out limits, partial-failure handling, and
 * storage of generated bytes as NORMAL chat attachments. The Worker
 * supplies ONLY prompt/count/closed size through the image_generate
 * tool — never provider URLs, credentials, filesystem destinations,
 * or attachment paths.
 *
 * Required chain: generate → STARK attachment → conversation →
 * optional attachment_import proposal → review → Accept → workspace.
 * The provider NEVER writes to the project directly.
 */

import {
  IMAGE_GENERATION_MODEL,
  MAX_GENERATED_IMAGES,
  providerSupportsImageGeneration
} from '../../shared/ai/image-capabilities'
import { createHash } from 'node:crypto'
import type { ChatAttachment } from '../../shared/chat-attachments/types'
import type { AiProviderService } from '../ai/ai-provider-service'
import { ProviderTimeoutError } from '../ai/errors'
import type { AiProviderAdapter, ProviderRegistry } from '../ai/provider-adapter'
import type { ChatAttachmentService } from '../chat-attachments/service'
import type { HeartService } from '../heart/heart-service'
import { HeartImageUnsupportedError } from '../heart/heart-errors'
import { MAX_IMAGE_PROMPT_CODEPOINTS, IMAGE_TOOL_OUTER_TIMEOUT_MS } from './limits'
import {
  ImageCapabilityUnsupportedError,
  ImageGenerationFailedError,
  ImageGenerationTimeoutError,
  ImageProviderUnavailableError,
  InvalidImageGenerationRequestError
} from './errors'
import { parseImageGenerateArgs } from './validation'

export interface GeneratedImageAttachment {
  readonly attachment: ChatAttachment
  readonly sha256: string
}

export interface ImageGenerationOutcome {
  readonly images: readonly GeneratedImageAttachment[]
  /** Successful images are kept; failures never retry automatically. */
  readonly failedCount: number
}

export interface ImageGenerationDeps {
  readonly providerService: AiProviderService
  readonly registry: ProviderRegistry
  readonly attachments: ChatAttachmentService
  /** Heart routing (optional). Absent in older harnesses — falls back to the fixed image model. */
  readonly heart?: HeartService
}

function extensionFor(mimeType: string): string {
  if (mimeType === 'image/jpeg') {
    return 'jpg'
  }
  if (mimeType === 'image/gif') {
    return 'gif'
  }
  if (mimeType === 'image/webp') {
    return 'webp'
  }
  return 'png'
}

/**
 * Races one provider call against the outer tool bound. The loser is
 * dropped bounded (its own per-call budget still applies); nothing
 * retries. Rejects with ImageGenerationTimeoutError on expiry.
 */
function withOuterBound<T>(timeoutMs: number, task: () => Promise<T>): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | null = null
  const timeout = new Promise<never>((_, reject) => {
    timer = setTimeout(() => {
      reject(new ImageGenerationTimeoutError())
    }, timeoutMs)
  })
  const guarded = task()
  guarded.catch(() => {
    // Best effort: a late provider rejection after the outer bound
    // already fired must never surface as unhandled.
  })
  return Promise.race([guarded, timeout]).finally(() => {
    if (timer !== null) {
      clearTimeout(timer)
    }
  })
}

export class ImageGenerationService {
  constructor(private readonly deps: ImageGenerationDeps) {}

  /**
   * Generates 1..4 images for one approved invocation. Returns every
   * valid completed image plus a safe failed count — successes are
   * never discarded on partial failure, and nothing retries.
   */
  async generateImages(input: { prompt: unknown; count: unknown; size?: unknown; outerTimeoutMs?: number }): Promise<ImageGenerationOutcome> {
    const validated = parseImageGenerateArgs({ prompt: input.prompt, count: input.count, ...(input.size === undefined ? {} : { size: input.size }) })
    if ([...validated.prompt].length > MAX_IMAGE_PROMPT_CODEPOINTS) {
      throw new InvalidImageGenerationRequestError()
    }
    const { adapter, apiKey, model } = await this.resolveImageAssignment()
    try {
      const generate = adapter.generateImages?.bind(adapter)
      if (generate === undefined) {
        throw new ImageCapabilityUnsupportedError()
      }
      // One bounded provider request with the full count: the
      // configured provider supports native multi-output, so fan-out
      // is unnecessary. At most one provider call per approved
      // invocation (trivially within the ≤2 concurrent bound), zero
      // retries — a short response is partial success, never a reason
      // to call again. The whole operation additionally races an
      // outer tool bound (180 seconds); the per-call budget (120
      // seconds) bounds the provider leg.
      const outerBound = typeof input.outerTimeoutMs === 'number' && Number.isFinite(input.outerTimeoutMs) && input.outerTimeoutMs > 0
        ? Math.min(input.outerTimeoutMs, IMAGE_TOOL_OUTER_TIMEOUT_MS)
        : IMAGE_TOOL_OUTER_TIMEOUT_MS
      let batch: readonly { readonly bytes: Uint8Array; readonly mimeType: string }[]
      try {
        batch = await withOuterBound(outerBound, () =>
          generate({ apiKey, model, prompt: validated.prompt, count: validated.count, ...(validated.size === undefined ? {} : { size: validated.size }) })
        )
      } catch (error) {
        if (error instanceof ImageGenerationTimeoutError) {
          throw error
        }
        batch = []
      }
      const stored: GeneratedImageAttachment[] = []
      let index = 0
      for (const image of batch.slice(0, validated.count)) {
        index += 1
        try {
          const bytes = Buffer.from(image.bytes)
          const attachment = await this.deps.attachments.createGeneratedImage({
            bytes,
            mimeType: image.mimeType,
            displayName: `generated-image-${String(index)}.${extensionFor(image.mimeType)}`
          })
          stored.push({ attachment, sha256: createHash('sha256').update(bytes).digest('hex') })
        } catch {
          // Invalid/oversize provider output is dropped bounded —
          // valid siblings are still returned.
        }
        if (stored.length >= MAX_GENERATED_IMAGES) {
          break
        }
      }
      if (stored.length === 0) {
        throw new ImageGenerationFailedError()
      }
      return { images: stored, failedCount: validated.count - stored.length }
    } catch (error) {
      if (
        error instanceof InvalidImageGenerationRequestError ||
        error instanceof ImageProviderUnavailableError ||
        error instanceof ImageCapabilityUnsupportedError ||
        error instanceof ImageGenerationTimeoutError ||
        error instanceof ImageGenerationFailedError
      ) {
        throw error
      }
      if (error instanceof ProviderTimeoutError) {
        throw new ImageGenerationTimeoutError({ cause: error })
      }
      throw new ImageGenerationFailedError({ cause: error })
    } finally {
      void apiKey
    }
  }

  /**
   * Heart-aware image routing: fixed incapable routes fail with an
   * explicit error; Auto-Swap may select an authorized configured
   * image-capable provider. No hidden unauthorized rerouting.
   */
  private async resolveImageAssignment(): Promise<{ adapter: AiProviderAdapter; apiKey: string; model: string }> {
    if (this.deps.heart !== undefined) {
      try {
        const snapshot = this.deps.heart.snapshot()
        const route = this.deps.heart.resolveWorkerForImageGeneration(snapshot, 'general')
        if (!providerSupportsImageGeneration(route.assignment.providerId, route.assignment.model)) {
          throw new ImageCapabilityUnsupportedError()
        }
        return await this.decryptFor(route.assignment.providerId, route.assignment.model)
      } catch (error) {
        if (error instanceof HeartImageUnsupportedError) {
          throw new ImageCapabilityUnsupportedError()
        }
        if (
          error instanceof ImageProviderUnavailableError ||
          error instanceof ImageCapabilityUnsupportedError
        ) {
          throw error
        }
        throw new ImageProviderUnavailableError()
      }
    }
    return await this.decryptFor('openai', IMAGE_GENERATION_MODEL)
  }

  private async decryptFor(
    providerId: string,
    model: string
  ): Promise<{ adapter: AiProviderAdapter; apiKey: string; model: string }> {
    const adapter = this.deps.registry.get(providerId as never)
    if (adapter === undefined || typeof adapter.generateImages !== 'function') {
      if (adapter === undefined) {
        throw new ImageProviderUnavailableError()
      }
      throw new ImageCapabilityUnsupportedError()
    }
    if (!providerSupportsImageGeneration(adapter.id, model)) {
      throw new ImageCapabilityUnsupportedError()
    }
    try {
      const apiKey = await this.deps.providerService.decryptCredentialForUse(providerId as never)
      return { adapter, apiKey, model }
    } catch {
      throw new ImageProviderUnavailableError()
    }
  }
}

